const data = {
  products: [
    {
      _id: '1',
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      image: '../images/p1.jpg',
      price: 120,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '2',
      name: 'Addidas Fit Shirt',
      category: 'Shirts',
      image: '../images/p2.jpg',
      price: 100,
      brand: 'Nike',
      rating: 4,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '3',
      name: 'Lacoste Free Shirt',
      category: 'Shirts',
      image: '../images/p3.jpg',
      price: 65,
      brand: 'Nike',
      rating: 3,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      _id: '4',
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      image: '../images/p4.jpg',
      price: 85,
      brand: 'Nike',
      rating: 2,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '5',
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      image: '../images/p5.jpg',
      price: 140,
      brand: 'Nike',
      rating: 3,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '6',
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      image: '../images/p6.jpg',
      price: 135,
      brand: 'Nike',
      rating: 2.5,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
}

export default data
